local open=false
local function nui(show,payload)
  open=show; SetNuiFocus(show,show); SendNUIMessage({action=show and 'open' or 'close', data=payload or {}})
end
CreateThread(function() Wait(1500); TriggerServerEvent('WB_Multichar:requestOpen') end)
RegisterNetEvent('esx:playerLoaded', function() end)
RegisterNetEvent('WB_Multichar:refresh', function() ESX.TriggerServerCallback('WB_Multichar:getCharacters', function(data) nui(true,data) end) end)
RegisterNetEvent('WB_Multichar:created', function() ESX.TriggerServerCallback('WB_Multichar:getCharacters', function(data) nui(true,data) end) end)
RegisterNetEvent('WB_Multichar:spawnCharacter', function(char)
  nui(false)
  local ped=PlayerPedId(); DoScreenFadeOut(400); Wait(500)
  local c = Config.DefaultSpawn; SetEntityCoords(ped,c.x,c.y,c.z); SetEntityHeading(ped,c.w); FreezeEntityPosition(ped,false)
  TriggerEvent('skinchanger:loadSkin', char.skin and json.decode(char.skin) or {})
  Wait(500); DoScreenFadeIn(800); TriggerEvent('WB_Identity:characterLoaded', char)
end)
RegisterNetEvent('WB_Multichar:open', function() ESX.TriggerServerCallback('WB_Multichar:getCharacters', function(data) nui(true,data) end) end)
RegisterNUICallback('select', function(d,cb) TriggerServerEvent('WB_Multichar:selectCharacter', d.id); cb({ok=true}) end)
RegisterNUICallback('create', function(d,cb) TriggerServerEvent('WB_Multichar:createCharacter', d); cb({ok=true}) end)
RegisterNUICallback('delete', function(d,cb) TriggerServerEvent('WB_Multichar:deleteCharacter', d.id); cb({ok=true}) end)
RegisterNUICallback('close', function(_,cb) nui(false); cb({ok=true}) end)
RegisterCommand('characters', function() TriggerEvent('WB_Multichar:open') end)
